// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var $btnGet, $btnThrow, $close, $content, $login, $msg, $post, $textarea;
    $btnThrow = $('#btnThrow');
    $btnGet = $('#btnGet');
    $post = $('#post');
    $login = $('#login');
    $content = $('#content');
    $close = $('.btn-close');
    $msg = $('#msg');
    $textarea = $('textarea');
    $close.on('click', function() {
      return $(this).parent().removeClass('active');
    });
    $post.find('button').on('click', function() {
      return $.post('/post', {
        content: $textarea.val()
      }, function(data) {
        return console.log(data);
      });
    });
    $btnThrow.on('click', function() {
      $post.addClass('active');
      return $textarea.val('').focus();
    });
    return $btnGet.on('click', function() {
      $msg.text('正在拔瓶子..');
      $content.addClass('active');
      return $.post('/', function(data) {
        if (data.code === 0) {
          return $msg.text(data.msg);
        } else {
          return $msg.text(data.msg.content);
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=index.map
