// Generated by CoffeeScript 1.7.1
$(function() {
  var $btnGet, $btnThrow, $close, $content, $login, $msg, $post, $textarea;
  $btnThrow = $('#btnThrow');
  $btnGet = $('#btnGet');
  $post = $('#post');
  $login = $('#login');
  $content = $('#content');
  $close = $('.btn-close');
  $msg = $('#msg');
  $textarea = $('textarea');
  $close.on('click', function() {
    return $(this).parent().removeClass('active');
  });
  $post.find('button').on('click', function() {
    $.post('/post', {
      content: $textarea.val()
    });
    return false;
  });
  $btnThrow.on('click', function() {
    $post.addClass('active');
    return $textarea.val('').focus();
  });
  return $btnGet.on('click', function() {
    $msg.text('正在拔瓶子..');
    $content.addClass('active');
    return $.post('/', function(data) {
      if (data.code === 0) {
        return $msg.text(data.msg);
      } else {
        return $msg.text(data.msg.content);
      }
    });
  });
});
